[phases.setup]
packages = ["python3", "ffmpeg"]

[phases.install]
cmds = ["python3 -m venv --copies /opt/venv", ". /opt/venv/bin/activate", "pip install -r requirements.txt"]

[phases.start]
cmd = "python3 bot.py"
